// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS6HwS-LYLdJwJotaEMrwtC96DmZGzLJg',
    appId: '1:134069715994:web:7e7c7008f395869af53da3',
    messagingSenderId: '134069715994',
    projectId: 'cinelib-54ce7',
    authDomain: 'cinelib-54ce7.firebaseapp.com',
    storageBucket: 'cinelib-54ce7.firebasestorage.app',
    measurementId: 'G-C2935JFHLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvuKkuHaoQzCj-HmZRwImyngWl9GZdst4',
    appId: '1:134069715994:android:64921b05c2534bc1f53da3',
    messagingSenderId: '134069715994',
    projectId: 'cinelib-54ce7',
    storageBucket: 'cinelib-54ce7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSRbL4Kp-4-zv4JuliO4yjuWxFM9GxMqs',
    appId: '1:134069715994:ios:9155b0dc97802d99f53da3',
    messagingSenderId: '134069715994',
    projectId: 'cinelib-54ce7',
    storageBucket: 'cinelib-54ce7.firebasestorage.app',
    iosBundleId: 'com.example.cinelib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSRbL4Kp-4-zv4JuliO4yjuWxFM9GxMqs',
    appId: '1:134069715994:ios:9155b0dc97802d99f53da3',
    messagingSenderId: '134069715994',
    projectId: 'cinelib-54ce7',
    storageBucket: 'cinelib-54ce7.firebasestorage.app',
    iosBundleId: 'com.example.cinelib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS6HwS-LYLdJwJotaEMrwtC96DmZGzLJg',
    appId: '1:134069715994:web:7d82847b0a420dbbf53da3',
    messagingSenderId: '134069715994',
    projectId: 'cinelib-54ce7',
    authDomain: 'cinelib-54ce7.firebaseapp.com',
    storageBucket: 'cinelib-54ce7.firebasestorage.app',
    measurementId: 'G-EMLB4EPPRJ',
  );
}
